build: false

environment:
    PYTHON: "C:\\Python37"

    CONAN_REFERENCE: "jmespath.cpp/0.2.0"
    CONAN_USERNAME: "robertmrk"
    CONAN_LOGIN_USERNAME: "robertmrk"
    CONAN_CHANNEL: "testing"
    CONAN_UPLOAD: "https://api.bintray.com/conan/robertmrk/conan"
    CONAN_ARCHS: "x86_64"

    matrix:
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          CONAN_VISUAL_VERSIONS: 15


install:
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip.exe install conan --upgrade
  - pip.exe install conan_package_tools
  - conan user # It creates the conan data directory

test_script:
  - python build.py
